server:
  port: 7788

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/baseApp
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
